language: python
python:
    - "2.7"
sudo: false
before_install:
    - pip install --user urllib3[secure] cpp-coveralls
install:
    - pip install -U platformio
script:
    - platformio remote test -e uno
after_success:
    - make test
    - coveralls --exclude unity --exclude json_unit_tests.c --gcov-options '\-lp'
