language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
script:
    - platformio remote test -e uno
after_success:
    # urllib3 should be installed after remote tests as is breaks remote requests
    - pip install urllib3[secure] cpp-coveralls
    - make test
    - coveralls --exclude unity --exclude test --exclude lib --gcov-options '\-lp'
